#!/usr/bin/env python3
"""
Generate V5's CSS custom properties from the Figma variable export.

    python3 build-tokens.py            # write css/tokens.*.css
    python3 build-tokens.py --check    # fail if the generated CSS is stale

Inputs (tokens/, committed — the source of truth):
    figma-foundations-variables.json   BETA-Foundations, all three collections
    local-layout.json                  the few names Figma does not define

Outputs (css/, all GENERATED — never hand-edit):
    tokens.primitives.css   collection "1 Primitives" — raw palette, type, spacing,
                            radius, shadow geometry. Components must not touch these.
    tokens.semantic.css     collections "2 Semantic" + "3 Theme" — the only layer
                            components may reference. Aliases stay as real var()
                            references so a primitive change propagates.
    tokens.local.css        local-layout.json — page furniture Figma has no opinion
                            on, plus the density mapping (see below).
    tokens.a11y.css         contrast overrides, one per measured WCAG failure.

How the export's modes become CSS:

    1 Primitives  Mode 1     -> :root
    2 Semantic    Desktop    -> :root
                  Mobile     -> @media (max-width: <local-layout $breakpoints.mobile>)
    3 Theme       Light      -> :root, :root[data-appearance="light"]
                  Dark       -> :root[data-appearance="dark"]

Density is NOT a Figma mode — the file ships `input.default.*` and `input.compact.*`
as separate token paths. local-layout.json maps them onto one set of names under
`:root` and `:root[data-density="compact"]`, so components reference `--field-height`
and the attribute picks the branch.

Names flatten mechanically from the token's path inside its collection, never
invented:
    color.action.primary  ->  --color-action-primary
    font/heading/md/size  ->  --font-heading-md-size
    spacing.0-5           ->  --spacing-0-5
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
TOKENS = ROOT / "tokens"
CSS = ROOT / "css"

EXPORT = "figma-foundations-variables.json"

BANNER = ("/* GENERATED by build-tokens.py from tokens/{src} — do not edit by hand. */\n"
          "/* Regenerate:  python3 v5/build-tokens.py */\n")

# Figma stores font-weight as a name string; CSS needs a number. Together with the
# shadow composition below, this is the only value translation the build performs.
WEIGHT_NUMBERS = {"thin": 100, "extralight": 200, "light": 300, "regular": 400,
                  "normal": 400, "medium": 500, "semibold": 600, "bold": 700,
                  "extrabold": 800, "black": 900}

FONT_STACK = ('"{family}", "Helvetica Neue", -apple-system, BlinkMacSystemFont, '
              '"Segoe UI", sans-serif')

# Figma models a shadow as separate y / blur / color variables, which CSS cannot use
# directly. These compose the three back into one box-shadow value. The parts stay
# available, and because the composition is pure var() it follows the theme.
SHADOW_STEPS = ("xs", "sm", "md", "lg")


# ---------------------------------------------------------------- name flattening

def var_name(path):
    """'color.action.primary' -> '--color-action-primary'"""
    parts = re.split(r"[./]", path)
    slug = "-".join(p.strip() for p in parts if p.strip()).lower()
    return "--" + re.sub(r"-+", "-", slug)


def is_alias(value):
    return isinstance(value, str) and value.startswith("{") and value.endswith("}")


def alias_to_var(value):
    """'{font-size.2xl}' -> 'var(--font-size-2xl)'

    An alias path is relative to the root of the collection it points at (named in
    the token's `$collectionName`), which is exactly what the flattened name is
    built from — so no prefix has to be stripped or added.
    """
    return f"var({var_name(value.strip()[1:-1])})"


# ------------------------------------------------------------------ flatten trees

def flatten(node, prefix=()):
    """Walk one mode's tree, yielding (path, token) for every leaf variable."""
    for key, val in node.items():
        if key.startswith("$"):
            continue
        path = prefix + (key,)
        if isinstance(val, dict) and "$value" in val:
            yield ".".join(path), val
        elif isinstance(val, dict):
            yield from flatten(val, path)


def css_value(token):
    """Render one variable's `$value` as CSS."""
    value, kind = token["$value"], token.get("$type")

    if is_alias(value):
        return alias_to_var(value)
    if kind == "color":
        # hex from Figma, or an rgba() for the scrim and shadow colours
        return value.upper() if value.startswith("#") else value
    if kind == "float":
        number = int(value) if float(value).is_integer() else value
        return "0" if number == 0 else f"{number}px"
    return str(value)


def emit(selector, decls, indent="  "):
    if not decls:
        return ""
    body = "".join(f"{indent}{name}: {value};\n" for name, value in decls)
    return f"{selector} {{\n{body}}}\n"


def load_export():
    """{collection name: {mode name: tree}} — the export is a list of one-key dicts."""
    raw = json.loads((TOKENS / EXPORT).read_text())
    collections = {}
    for entry in raw:
        for name, body in entry.items():
            collections[name] = body["modes"]
    return collections


def mode_decls(tree, transform=None):
    decls = []
    for path, token in flatten(tree):
        name = var_name(path)
        decls.append((name, css_value(token)))
    if transform:
        decls = [transform(name, value) for name, value in decls]
    return decls


# ---------------------------------------------------------------------- builders

def build_primitives(collections):
    tree = collections["1 Primitives"]["Mode 1"]
    decls = []

    for path, token in flatten(tree):
        name = var_name(path)
        if path.startswith("font-family."):
            decls.append((name, FONT_STACK.format(family=token["$value"])))
        elif path.startswith("font-weight."):
            key = str(token["$value"]).strip().lower().replace(" ", "")
            if key not in WEIGHT_NUMBERS:
                raise SystemExit(f"unknown font weight name: {token['$value']!r} ({path})")
            decls.append((name, str(WEIGHT_NUMBERS[key])))
        else:
            decls.append((name, css_value(token)))

    out = BANNER.format(src=EXPORT)
    out += ('/* Collection "1 Primitives" (mode: Mode 1). The raw palette, type scale,\n'
            "   spacing, radius and shadow geometry. Components must NEVER reference a\n"
            "   primitive directly — go through tokens.semantic.css. */\n\n")
    out += emit(":root", decls)
    return out


def build_semantic(collections, breakpoints):
    semantic = collections["2 Semantic"]
    theme = collections["3 Theme"]

    out = BANNER.format(src=EXPORT)
    out += ("/* The only layer components may reference. Values stay as var() aliases,\n"
            "   never resolved hexes, so editing a primitive propagates the way it does\n"
            "   in Figma.\n\n"
            '   Collection "2 Semantic" carries a Desktop/Mobile axis and\n'
            '   collection "3 Theme" a Light/Dark axis, so the two compose:\n'
            "     viewport   -> a media query (breakpoint below)\n"
            '     appearance -> data-appearance="light|dark" on <html> */\n\n')

    out += '/* "2 Semantic" — mode Desktop */\n'
    out += emit(":root", mode_decls(semantic["Desktop"]))

    # The export says which values change on Mobile but not at what width. The
    # breakpoint is the one thing that has to come from local-layout.json, because
    # CSS cannot read a custom property inside a media query.
    mobile = breakpoints["mobile"]
    desktop_decls = dict(mode_decls(semantic["Desktop"]))
    mobile_decls = [(n, v) for n, v in mode_decls(semantic["Mobile"])
                    if desktop_decls.get(n) != v]
    out += (f'\n/* "2 Semantic" — mode Mobile. Only the {len(mobile_decls)} variables that '
            f"actually differ\n   from Desktop are re-declared. The {mobile} breakpoint is "
            "NOT in the export —\n   it comes from $breakpoints in local-layout.json. */\n")
    out += f"@media (max-width: {mobile}) {{\n"
    out += "".join(f"  {line}\n" for line in emit(":root", mobile_decls).splitlines())
    out += "}\n"

    out += '\n/* "3 Theme" — mode Light */\n'
    out += emit(':root, :root[data-appearance="light"]', mode_decls(theme["Light"]))
    out += '\n/* "3 Theme" — mode Dark */\n'
    out += emit(':root[data-appearance="dark"]', mode_decls(theme["Dark"]))

    composed = [(f"--shadow-{step}",
                 f"0 var(--shadow-{step}-y) var(--shadow-{step}-blur) var(--shadow-{step}-color)")
                for step in SHADOW_STEPS]
    out += ("\n/* Figma models a shadow as separate y / blur / color variables. These\n"
            "   compose them into usable box-shadow values; the composition is pure\n"
            "   var(), so the colour still follows the theme. */\n")
    out += emit(":root", composed)
    return out


def build_local(local):
    out = BANNER.format(src="local-layout.json")
    out += "/* " + "\n   ".join(local["$comment"]) + " */\n\n"

    for set_name, spec in local["sets"].items():
        decls = [(var_name(path), alias_to_var(value) if is_alias(value) else value)
                 for path, value in spec["tokens"].items()]
        if spec.get("$comment"):
            out += "/* " + "\n   ".join(spec["$comment"]) + " */\n"
        out += f"/* set: {set_name} */\n"
        out += emit(spec["selector"], decls) + "\n"
    return out.rstrip("\n") + "\n"


# ------------------------------------------------------------------- contrast pass

def relative_luminance(color):
    hex_color = color.lstrip("#")
    channels = [int(hex_color[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    linear = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a, b):
    la, lb = sorted((relative_luminance(a), relative_luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def resolver(collections, appearance):
    primitives = {path: token["$value"].upper()
                  for path, token in flatten(collections["1 Primitives"]["Mode 1"])
                  if token.get("$type") == "color"}
    theme = dict(flatten(collections["3 Theme"]["Light" if appearance == "light" else "Dark"]))

    def resolve(path):
        value = theme[path]["$value"]
        return primitives[value.strip()[1:-1]] if is_alias(value) else value.upper()

    def ramp_of(path):
        """('teal', 500) for a token aliased to a step of the teal ramp."""
        value = theme[path]["$value"]
        if not is_alias(value):
            return None, None
        family, _, step = value.strip()[1:-1].rpartition(".")
        return family, int(step)

    def ramp(family, current=None):
        """Steps of one ramp, ordered by nearness to `current`.

        Nearest-first keeps every override the smallest possible move. Ordering by
        lightness instead would "fix" a dark border by making it pure white.
        """
        steps = sorted((int(k.split(".")[1]), v) for k, v in primitives.items()
                       if k.startswith(family + "."))
        keys = [k for k, _ in steps]
        origin = keys.index(current) if current in keys else 0
        return [(k, v) for k, v in sorted(
            steps, key=lambda s: (abs(keys.index(s[0]) - origin), keys.index(s[0])))]

    return resolve, ramp, ramp_of


# (foreground, background, threshold, which side to move to fix)
# 4.5 = WCAG 1.4.3 body text. 3.0 = WCAG 1.4.11 UI component boundary.
CHECKS = [
    ("color.text.primary",           "color.background.surface",     4.5, "fg"),
    ("color.text.primary",           "color.background.page",        4.5, "fg"),
    ("color.text.secondary",         "color.background.surface",     4.5, "fg"),
    ("color.text.secondary",         "color.background.page",        4.5, "fg"),
    ("color.text.link",              "color.background.surface",     4.5, "fg"),
    ("color.on.primary",             "color.action.primary",         4.5, "bg"),
    ("color.on.primary",             "color.action.primary-hover",   4.5, "bg"),
    ("color.on.danger",              "color.action.danger",          4.5, "bg"),
    # The system has no text-accent token, so accent text (subheads, the selected
    # chip, the add button) borrows color.action.primary. Both surfaces it lands on
    # are measured, which is why that token carries three constraints at once.
    ("color.action.primary",         "color.background.surface",     4.5, "fg"),
    ("color.action.primary",         "color.action.primary-subtle",  4.5, "fg"),
    # inline validation text sits on the field's own surface, and in a banner
    ("color.feedback.error-strong",  "color.background.surface",     4.5, "fg"),
    ("color.feedback.error-strong",  "color.feedback.error-subtle",  4.5, "fg"),
    ("color.feedback.success-strong", "color.feedback.success-subtle", 4.5, "fg"),
    ("color.feedback.info-strong",   "color.feedback.info-subtle",   4.5, "fg"),
    # An input's border is the only thing identifying it as a control, so 1.4.11
    # applies to it. A filled button's fill is deliberately not checked: it is
    # identified by its own label, which is measured above.
    ("color.border.default",         "color.background.surface",     3.0, "fg"),
    ("color.border.focus",           "color.background.surface",     3.0, "fg"),
    ("color.border.error",           "color.background.surface",     3.0, "fg"),
    # color.text.disabled is deliberately absent: 1.4.3 exempts text in an inactive
    # control, and forcing 4.5:1 would make a disabled field look active.
]

# Failures whose auto-fix is declined, per appearance. The pair is still measured and
# still reported as a FAIL — it is only left un-re-pointed, and the generated file
# says so, so an accepted failure never reads as a passing one.
#   light border.default: a design decision. The field outline is meant to be the
#   export's own neutral.300 hairline; neutral.500 clears 1.4.11 but reads as a
#   heavier control than the design intends.
# Dark deliberately keeps its fix: there the export's neutral.800 border is the same
# colour as the neutral.800 card behind it, so the field would have no edge at all.
ACCEPTED = {
    ("light", "color.border.default"):
        "design decision — the field outline is meant to be the export's neutral.300 "
        "hairline. Revisit if the fields stop reading as controls.",
}


def build_a11y(collections):
    sections, report = [], []

    for appearance in ("light", "dark"):
        resolve, ramp, ramp_of = resolver(collections, appearance)
        overrides, notes = [], []

        # A token can appear in several checks. Collect every constraint on it first,
        # then solve them together — fixing one pair at a time emits duplicate
        # declarations where the last one wins and re-breaks the earlier pair.
        constraints, violated = {}, set()
        for fg_path, bg_path, threshold, side in CHECKS:
            target = fg_path if side == "fg" else bg_path
            other = bg_path if side == "fg" else fg_path
            ratio = contrast(resolve(fg_path), resolve(bg_path))
            constraints.setdefault(target, []).append((other, resolve(other), threshold, ratio))
            verdict = "PASS" if ratio >= threshold else "FAIL"
            if verdict == "FAIL":
                violated.add(target)
            report.append(f"  {verdict}  {ratio:5.2f}:1  (needs {threshold})  "
                          f"{appearance:<5} {fg_path} on {bg_path}")

        for target in sorted(violated):
            reqs = constraints[target]
            family, step = ramp_of(target)
            worst = min(reqs, key=lambda r: r[3])

            if (appearance, target) in ACCEPTED:
                report.append(f"  KEEP  {target} ({appearance}) — accepted at "
                              f"{worst[3]:.2f}:1 vs {worst[0]}, not re-pointed")
                notes.append(f"/* ACCEPTED FAILURE — {target} keeps its export value in "
                             f"{appearance}: {worst[3]:.2f}:1 vs {worst[0]}, needs "
                             f"{worst[2]}:1. {ACCEPTED[(appearance, target)]} */")
                continue

            solution = next(((key, hex_) for key, hex_ in (ramp(family, step) if family else [])
                             if all(contrast(hex_, other) >= threshold
                                    for _, other, threshold, _ in reqs)), None)

            if not solution:
                report.append(f"  GAP   {target} ({appearance}) — no step of `{family}` "
                              f"satisfies all {len(reqs)} constraint(s), NOT FIXED")
                notes.append(f"/* PALETTE GAP — {target} needs "
                             + ", ".join(f"{t}:1 vs {p}" for p, _, t, _ in reqs)
                             + f"; best today is {worst[3]:.2f}:1 vs {worst[0]}. No step of "
                             f"the `{family}` ramp satisfies it — needs a new primitive. */")
                continue

            key, hex_ = solution
            achieved = ", ".join(f"{contrast(hex_, other):.2f}:1 vs {p}"
                                 for p, other, _, _ in reqs)
            overrides.append((var_name(target), f"var({var_name(f'{family}.{key}')})", achieved))
            report.append(f"  FIX   {target} ({appearance}) -> {family}.{key}  [{achieved}]")

        if overrides:
            selector = ':root, :root[data-appearance="light"]' if appearance == "light" \
                else ':root[data-appearance="dark"]'
            body = "".join(f"  {name}: {value};  /* {why} */\n"
                           for name, value, why in sorted(set(overrides)))
            sections.append(f"/* {appearance} */\n{selector} {{\n{body}}}\n")
        if notes:
            sections.append("\n".join(notes) + "\n")

    out = BANNER.format(src=f"{EXPORT} (contrast pass)")
    out += ("/* Every declaration below is a measured WCAG failure in the export as it\n"
            "   stands, re-pointed to the nearest step of its OWN ramp that clears the\n"
            "   threshold. Nothing is invented — each line is a one-line change to make\n"
            "   in Figma, after which this file shrinks.\n"
            "   4.5:1 = WCAG 1.4.3 (text) · 3:1 = WCAG 1.4.11 (UI component boundary).\n"
            "   Load AFTER tokens.semantic.css. Remove the <link> to see the file's own\n"
            "   values. */\n\n")
    out += "\n".join(sections) if sections else "/* No failures — nothing to override. */\n"
    return out, report


# ------------------------------------------------------------- dangling-var check

# Files that consume the tokens. They may declare their own local variables
# (--page-bg and friends), so they count as sources of definitions too.
CONSUMERS = ["css/components.css", "index.html", "app.js"]

DEFINED_RE = re.compile(r"^\s*(--[\w-]+)\s*:", re.M)
USED_RE = re.compile(r"var\(\s*(--[\w-]+)")


def dangling_vars(outputs):
    """Names referenced with var() but declared nowhere.

    A token that lives only in the generated CSS and not in a source JSON
    disappears silently on the next build — the CSS still parses, the property
    just resolves to nothing and the component collapses. Catch it here."""
    text = "\n".join(outputs.values())
    for rel in CONSUMERS:
        path = ROOT / rel
        if path.exists():
            text += "\n" + path.read_text()

    defined = set(DEFINED_RE.findall(text))
    return sorted(set(USED_RE.findall(text)) - defined)


# ----------------------------------------------------------------------------- main

def main():
    check_only = "--check" in sys.argv

    collections = load_export()
    local = json.loads((TOKENS / "local-layout.json").read_text())

    a11y, report = build_a11y(collections)
    outputs = {
        "tokens.primitives.css": build_primitives(collections),
        "tokens.semantic.css": build_semantic(collections, local["$breakpoints"]),
        "tokens.local.css": build_local(local),
        "tokens.a11y.css": a11y,
    }

    dangling = dangling_vars(outputs)

    stale = []
    for filename, content in outputs.items():
        path = CSS / filename
        if check_only:
            if not path.exists() or path.read_text() != content:
                stale.append(filename)
        else:
            path.write_text(content)
            print(f"wrote css/{filename}  ({len(content.splitlines())} lines)")

    print("\ncontrast pass (WCAG 1.4.3 / 1.4.11):")
    print("\n".join(report))
    failures = sum(1 for line in report if line.strip().startswith(("FIX", "GAP")))
    accepted = sum(1 for line in report if line.strip().startswith("KEEP"))
    print(f"\n{failures} of {len(report)} measured pairs needed an override"
          + (f", {accepted} accepted as-is." if accepted else "."))

    if dangling:
        print("\nDANGLING var() references — used but declared nowhere:")
        print("\n".join(f"  {name}" for name in dangling))
        print("Add them to tokens/local-layout.json, or stop referencing them.")

    if check_only and stale:
        print("\nSTALE: " + ", ".join(stale))
        return 1
    if dangling:
        return 1
    if check_only:
        print("\nGenerated CSS is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
