#!/usr/bin/env python3
"""
Generate V5's CSS custom properties from the Finlink Core token sources.

    python3 build-tokens.py            # write css/tokens*.css
    python3 build-tokens.py --check    # fail if the generated CSS is stale

Inputs (tokens/, committed — the source of truth):
    finlink-core.json       the contract: Finlink Core Primitives, Finlink Core
                            Semantics, Default (typography). Transcribed from
                            FINLINK-DESIGN-TOKENS.md §4; the real Figma export
                            drops in here unchanged when it lands.
    finlink-core-ext.json   everything the contract cannot express and this
                            product still needs. Every set carries a gap ID.

Outputs (css/, all GENERATED — never hand-edit):
    tokens.css      §5.1-5.5. Layer 1 primitives (private --_ds-), the public
                    spacing/radius/border/opacity/sizing aliases, Layer 2
                    semantic colour, the 14 typography roles and their
                    .ds-text-* classes, and the base reset.
    tokens.ext.css  the extension layer — dark appearance, elevation, density,
                    the mobile type ramp, focus geometry and layout furniture.
    tokens.a11y.css contrast overrides, one per measured WCAG failure, in both
                    appearances.

The layer rule, and the one thing this build exists to enforce:

    Layer 3 -> Layer 2 -> Layer 1.  Never skip, never reverse.

    --_ds-*   PRIVATE. Primitives. components.css must never name one.
    --ds-*    PUBLIC. Semantics, typography roles, and the four scales that
              have no semantic layer yet (spacing, radius, border-width,
              opacity, sizing — the documented §4.4 exception, gap G-07).

Names flatten mechanically from the token's path inside its collection, then
take the prefix its layer earns. Nothing is invented:

    color.grey.0                            ->  --_ds-color-grey-0
    color.background.brand.bold.default     ->  --ds-color-background-brand-bold-default
    typography.body.md.strong.fontSize      ->  --ds-typography-body-md-strong-font-size
    space.16                                ->  --ds-spacing-16

Two members of the source are deliberately never emitted:
    font.style.*   Figma-only strings (Regular/Medium/SemiBold). Roles alias
                   font.weight instead, so the mapping never reaches CSS.
    the `space` group's contract key spelling — see G-12, fixed at source.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
TOKENS = ROOT / "tokens"
CSS = ROOT / "css"

CORE = "finlink-core.json"
EXT = "finlink-core-ext.json"

PRIVATE = "--_ds-"
PUBLIC = "--ds-"

BANNER = ("/* GENERATED by build-tokens.py from tokens/{src} — do not edit by hand. */\n"
          "/* Regenerate:  python3 build-tokens.py */\n")

WEIGHT_NUMBERS = {"thin": 100, "extralight": 200, "light": 300, "regular": 400,
                  "normal": 400, "medium": 500, "semibold": 600, "bold": 700,
                  "extrabold": 800, "black": 900}

# Primitive groups that also get a public mirror, because components consume them
# directly — there is no semantic layer for them yet (§4.4, G-07). `space` is not
# listed: it is public-only, and renamed on the way out.
PUBLIC_MIRRORS = ("radius", "border.width", "opacity", "sizing", "font.family")

# The four members of a typography role, and the CSS suffix each earns.
TYPO_PROPS = (("fontSize", "font-size"), ("lineHeight", "line-height"),
              ("letterSpacing", "letter-spacing"), ("fontWeight", "font-weight"))

ROOT_FONT_PX = 16          # every rem in this system assumes a 16px root (§5.5)
SHADOW_STEPS = ("xs", "sm", "md", "lg")


# ---------------------------------------------------------------- name flattening

def slug(path):
    """'color.action.primary' -> 'color-action-primary' (no prefix)."""
    parts = re.split(r"[./]", path)
    return re.sub(r"-+", "-", "-".join(p.strip() for p in parts if p.strip()).lower())


def is_alias(value):
    return isinstance(value, str) and value.startswith("{") and value.endswith("}")


def alias_path(value):
    return value.strip()[1:-1]


def fmt_num(value):
    """3.0 -> '3', 1.07692 -> '1.0769'. Trailing zeros never reach the CSS."""
    number = round(float(value), 4)
    if number == int(number):
        return str(int(number))
    return f"{number}".rstrip("0").rstrip(".")


def px(value):
    return "0px" if float(value) == 0 else f"{fmt_num(value)}px"


# ------------------------------------------------------------------ flatten trees

def flatten(node, prefix=()):
    """Walk one mode's tree, yielding (path, token) for every leaf variable."""
    for key, val in node.items():
        if key.startswith("$"):
            continue
        path = prefix + (key,)
        if isinstance(val, dict) and "$value" in val:
            yield ".".join(path), val
        elif isinstance(val, dict):
            yield from flatten(val, path)


def emit(selector, decls, indent="  "):
    if not decls:
        return ""
    body = "".join(f"{indent}{name}: {value};\n" for name, value in decls)
    return f"{selector} {{\n{body}}}\n"


def load_core():
    """{collection name: {mode name: tree}} — the export is a list of one-key dicts."""
    raw = json.loads((TOKENS / CORE).read_text())
    collections = {}
    for entry in raw:
        for name, body in entry.items():
            collections[name] = body["modes"]
    return collections


# ---------------------------------------------------------------------- layer 1

def primitive_value(path, token):
    value, kind = token["$value"], token.get("$type")
    if kind == "color":
        return value.upper() if value.startswith("#") else value
    if kind == "fontWeight":
        key = str(value).strip().lower().replace(" ", "")
        if key not in WEIGHT_NUMBERS:
            raise SystemExit(f"unknown font weight name: {value!r} ({path})")
        return str(WEIGHT_NUMBERS[key])
    if kind == "dimension":
        return px(value)
    if kind == "number":
        return fmt_num(value)
    return str(value)


def build_primitives(collections):
    """Layer 1 plus the public aliases of §5.2. Returns (css, {path: raw value})."""
    tree = collections["Finlink Core Primitives"]["Mode 1"]
    private, spacing, mirrors, raw = [], [], [], {}

    for path, token in flatten(tree):
        raw[path] = token["$value"]
        rendered = primitive_value(path, token)
        if path.startswith("space."):
            spacing.append((f"{PUBLIC}spacing-{path.split('.', 1)[1]}", rendered))
            continue
        name = PRIVATE + slug(path)
        private.append((name, rendered))
        if any(path.startswith(group + ".") for group in PUBLIC_MIRRORS):
            mirrors.append((PUBLIC + slug(path), f"var({name})"))

    out = ("/* ============================================================\n"
           "   LAYER 1 — PRIMITIVES  (private: never reference in components)\n"
           "   Source: Finlink Core Primitives\n"
           "   ============================================================ */\n")
    out += emit(":root", private)
    out += ("\n/* ============================================================\n"
            "   SPACING — public primitive alias (no semantic layer yet, G-07)\n"
            "   Keys are pixel values. The contract's source spells them\n"
            "   `space.--ds-spacing-16`, which any generator that concatenates\n"
            "   group + key turns into --ds-space---ds-spacing-16 (G-12); the\n"
            "   keys are clean here, which is the contract's own fix.\n"
            "   ============================================================ */\n")
    out += emit(":root", spacing + mirrors)
    return out, raw


# ---------------------------------------------------------------------- layer 2

def build_semantics(collections, primitive_paths):
    tree = collections["Finlink Core Semantics"]["Light"]
    decls = []
    for path, token in flatten(tree):
        value = token["$value"]
        if not is_alias(value):
            raise SystemExit(f"semantic {path} holds a raw value — semantics are alias-only")
        target = alias_path(value)
        if target not in primitive_paths:
            raise SystemExit(f"semantic {path} aliases {target}, which no primitive defines")
        decls.append((PUBLIC + slug(path), f"var({PRIVATE}{slug(target)})"))

    out = ("\n/* ============================================================\n"
           "   LAYER 2 — SEMANTIC COLOR  (public API: use these in components)\n"
           "   Source: Finlink Core Semantics — every value is an alias\n"
           "   ============================================================ */\n")
    return out + emit(":root", decls)


def role_paths(collections):
    """['heading.xl', ..., 'body.sm.default'] in authored order."""
    tree = collections["Default"]["Mode 1"]["typography"]
    seen = []
    for path, _ in flatten(tree):
        role = path.rsplit(".", 1)[0]
        if role not in seen:
            seen.append(role)
    return seen


def build_typography(collections, raw):
    """§5.4. font-size px->rem and line-height px->ratio are derived here, once."""
    tree = collections["Default"]["Mode 1"]["typography"]
    tokens = {path: token for path, token in flatten(tree)}
    decls, classes = [], []

    for role in role_paths(collections):
        values = {}
        for prop, suffix in TYPO_PROPS:
            token = tokens[f"{role}.{prop}"]
            value = token["$value"]
            values[prop] = raw[alias_path(value)] if is_alias(value) else value

        size_px = float(values["fontSize"])
        line_px = float(values["lineHeight"])
        weight = str(values["fontWeight"]).strip().lower()
        if weight not in WEIGHT_NUMBERS:
            raise SystemExit(f"unknown font weight name: {weight!r} (typography.{role})")

        base = f"{PUBLIC}typography-{slug(role)}"
        decls += [
            (f"{base}-font-size", f"{fmt_num(size_px / ROOT_FONT_PX)}rem"),
            (f"{base}-line-height", fmt_num(line_px / size_px)),
            (f"{base}-letter-spacing", px(values["letterSpacing"])),
            (f"{base}-font-weight", str(WEIGHT_NUMBERS[weight])),
        ]
        classes.append(f".ds-text-{slug(role)} {{\n"
                       f"  font-family: var({PUBLIC}font-family-sans);\n"
                       f"  font-size: var({base}-font-size);\n"
                       f"  line-height: var({base}-line-height);\n"
                       f"  letter-spacing: var({base}-letter-spacing);\n"
                       f"  font-weight: var({base}-font-weight);\n}}")

    out = ("\n/* ============================================================\n"
           "   TYPOGRAPHY ROLES — Source: Default collection\n"
           "   font-size  : rem (÷16 root)\n"
           "   line-height: unitless ratio, derived from the Figma px value, so\n"
           "                the layout survives the 1.4.12 text-spacing override\n"
           "   font-weight: mapped from the role's font.weight alias. Figma's\n"
           "                font.style strings never reach CSS.\n"
           "   ============================================================ */\n")
    out += emit(":root", decls)
    out += ("\n/* Apply as a whole role — never set the members individually.\n"
            "   components.css binds its own selectors alongside these, one role\n"
            "   per node, rather than putting a class on every text node. */\n")
    out += "\n".join(classes) + "\n"
    return out


BASE_RESET = """
/* ============================================================
   BASE — §5.5
   ============================================================ */
:root {
  /* All rem maths in this system assumes a 16px root.
     Do not set html { font-size: 62.5% } — it will break every role. */
  font-size: 100%;
}

body {
  font-family: var(--ds-font-family-sans);
  background-color: var(--ds-surface-page);
  color: var(--ds-color-text-neutral-bold-default);
  /* body.md.default is the document default */
  font-size: var(--ds-typography-body-md-default-font-size);
  line-height: var(--ds-typography-body-md-default-line-height);
  letter-spacing: var(--ds-typography-body-md-default-letter-spacing);
  font-weight: var(--ds-typography-body-md-default-font-weight);
  -webkit-font-smoothing: antialiased;
}

/* INTERIM G-06 — no tabular-figures token exists. Unaligned digits in a
   money column are a correctness problem, not a polish one, so the utility
   ships and the gap is logged. */
.ds-numeric {
  font-variant-numeric: tabular-nums;
  font-feature-settings: 'tnum' 1;
}
"""


def build_tokens_css(collections):
    primitives, raw = build_primitives(collections)
    out = BANNER.format(src=CORE)
    out += ("/* The only file permitted to contain literal values. Regenerate it whole;\n"
            "   never hand-edit a line. Load first, before any other stylesheet. */\n\n")
    out += primitives
    out += build_semantics(collections, set(raw))
    out += build_typography(collections, raw)
    out += BASE_RESET
    return out, raw


# ------------------------------------------------------------- extension layer

def ext_value(value, primitive_paths, semantic_paths):
    """Resolve one extension value. Aliases may point at either public layer."""
    if not is_alias(value):
        return value
    target = alias_path(value)
    if target in semantic_paths:
        return f"var({PUBLIC}{slug(target)})"
    if target in primitive_paths:
        return f"var({PRIVATE}{slug(target)})"
    raise SystemExit(f"extension aliases {target}, which neither layer defines")


def build_ext(ext, primitive_paths, semantic_paths):
    out = BANNER.format(src=EXT)
    out += "/* " + "\n   ".join(ext["$comment"]) + " */\n"

    for set_name, spec in ext["sets"].items():
        decls = [(f"--{slug(path)}", ext_value(value, primitive_paths, semantic_paths))
                 for path, value in spec["tokens"].items()]
        out += "\n"
        if spec.get("$comment"):
            out += "/* " + "\n   ".join(spec["$comment"]) + " */\n"
        out += f"/* set: {set_name} */\n"
        if not decls:
            out += f"/* {spec['selector']} — no overrides. */\n"
            continue
        block = emit(spec["selector"], decls)
        if spec.get("media"):
            out += f"@media {spec['media']} {{\n"
            out += "".join(f"  {line}\n" for line in block.splitlines())
            out += "}\n"
        else:
            out += block

    composed = [(f"{PUBLIC}shadow-{step}",
                 f"0 var({PUBLIC}shadow-{step}-y) var({PUBLIC}shadow-{step}-blur) "
                 f"var({PUBLIC}shadow-{step}-color)")
                for step in SHADOW_STEPS]
    out += ("\n/* Figma models a shadow as separate y / blur / colour variables. These\n"
            "   compose them into usable box-shadow values; the composition is pure\n"
            "   var(), so the colour still follows the appearance. INTERIM G-15. */\n")
    out += emit(":root", composed)
    return out


# ------------------------------------------------------------------- contrast pass

def relative_luminance(color):
    hex_color = color.lstrip("#")
    channels = [int(hex_color[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    linear = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a, b):
    la, lb = sorted((relative_luminance(a), relative_luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


EXT_VAR_RE = re.compile(r"var\(\s*(--[\w-]+)\s*\)")


def resolver(collections, ext, appearance):
    """(resolve, ramp, ramp_of) for one appearance.

    Dark is Finlink's semantics with the extension layer's overrides applied on
    top — the same composition the browser performs — so the pass measures what
    actually renders rather than what the contract alone would render.
    """
    primitives = {path: token["$value"].upper()
                  for path, token in flatten(collections["Finlink Core Primitives"]["Mode 1"])
                  if token.get("$type") == "color"}
    by_var = {PRIVATE + slug(path): value for path, value in primitives.items()}
    for path, value in ext["sets"]["ext-primitives"]["tokens"].items():
        by_var["--" + slug(path)] = value.upper()

    semantics = {path: token["$value"]
                 for path, token in flatten(collections["Finlink Core Semantics"]["Light"])}
    overrides = {}
    if appearance == "dark":
        for path, value in ext["sets"]["appearance-dark"]["tokens"].items():
            name = slug(path)
            if name.startswith("ds-color-"):
                overrides[name[len("ds-"):]] = value

    def resolve(path):
        key = slug(path)
        value = overrides.get(key, semantics[path])
        if is_alias(value):
            return primitives[alias_path(value)]
        match = EXT_VAR_RE.fullmatch(value.strip())
        if match:
            return by_var[match.group(1)]
        return value.upper()

    def ramp_of(path):
        """('color.teal', 500) for a token aliased to a step of the teal ramp."""
        value = overrides.get(slug(path), semantics[path])
        if not is_alias(value):
            return None, None
        family, _, step = alias_path(value).rpartition(".")
        return family, int(step)

    def ramp(family, current=None):
        """Steps of one ramp, ordered by nearness to `current`.

        Nearest-first keeps every override the smallest possible move. Ordering
        by lightness instead would "fix" a dark border by making it pure white.
        """
        steps = sorted((int(k.rpartition(".")[2]), v) for k, v in primitives.items()
                       if k.startswith(family + "."))
        keys = [k for k, _ in steps]
        origin = keys.index(current) if current in keys else 0
        return [(k, v) for k, v in sorted(
            steps, key=lambda s: (abs(keys.index(s[0]) - origin), keys.index(s[0])))]

    return resolve, ramp, ramp_of


# (foreground, background, threshold, which side to move to fix)
# 4.5 = WCAG 1.4.3 body text. 3.0 = WCAG 1.4.11 UI component boundary.
CHECKS = [
    ("color.text.neutral.bold.default",    "color.background.neutral.subtlest.default", 4.5, "fg"),
    ("color.text.neutral.bold.default",    "color.background.neutral.subtle.default",   4.5, "fg"),
    ("color.text.neutral.subtle.default",  "color.background.neutral.subtlest.default", 4.5, "fg"),
    ("color.text.neutral.subtle.default",  "color.background.neutral.subtle.default",   4.5, "fg"),
    # A filled button's label is what identifies it, so the fill moves, not the label.
    ("color.text.neutral.inverse.default", "color.background.brand.bold.default",       4.5, "bg"),
    ("color.text.neutral.inverse.default", "color.background.brand.bold.hovered",       4.5, "bg"),
    ("color.text.neutral.inverse.default", "color.background.danger.bold.default",      4.5, "bg"),
    # Accent text — subheads, the selected chip, the add button — lands on two
    # surfaces, which is why text.brand.bold carries two constraints at once.
    ("color.text.brand.bold.default",      "color.background.neutral.subtlest.default", 4.5, "fg"),
    ("color.text.brand.bold.default",      "color.background.brand.subtlest.default",   4.5, "fg"),
    # inline validation sits on the field's own surface, and in a banner
    ("color.text.danger.bold.default",     "color.background.neutral.subtlest.default", 4.5, "fg"),
    ("color.text.danger.bold.default",     "color.background.danger.subtlest.default",  4.5, "fg"),
    ("color.text.success.bold.default",    "color.background.success.subtlest.default", 4.5, "fg"),
    ("color.text.info.bold.default",       "color.background.info.subtlest.default",    4.5, "fg"),
    # An input's border is the only thing identifying it as a control, so 1.4.11
    # applies to it.
    ("color.border.neutral.bold.default",  "color.background.neutral.subtlest.default", 3.0, "fg"),
    ("color.border.brand.bold.default",    "color.background.neutral.subtlest.default", 3.0, "fg"),
    ("color.border.danger.bold.default",   "color.background.neutral.subtlest.default", 3.0, "fg"),
    # text.*.disabled is deliberately absent: 1.4.3 exempts text in an inactive
    # control, and forcing 4.5:1 would make a disabled field look active.
]

# Failures whose auto-fix is declined, per appearance. The pair is still measured
# and still reported as a FAIL — it is only left un-re-pointed, and the generated
# file says so, so an accepted failure never reads as a passing one.
ACCEPTED = {
    ("light", "color.border.neutral.bold.default"):
        "design decision — the field outline is meant to be the contract's own "
        "grey.300 hairline. §8.4 says use border.neutral.bold.hovered as the "
        "resting input border instead; components.css does exactly that, so the "
        "token itself is left alone for the dividers that still want it.",
}


def build_a11y(collections, ext):
    sections, report = [], []

    for appearance in ("light", "dark"):
        resolve, ramp, ramp_of = resolver(collections, ext, appearance)
        overrides, notes = [], []

        # A token can appear in several checks. Collect every constraint on it
        # first, then solve them together — fixing one pair at a time emits
        # duplicate declarations where the last one wins and re-breaks the first.
        constraints, violated = {}, set()
        for fg_path, bg_path, threshold, side in CHECKS:
            target = fg_path if side == "fg" else bg_path
            other = bg_path if side == "fg" else fg_path
            ratio = contrast(resolve(fg_path), resolve(bg_path))
            constraints.setdefault(target, []).append((other, resolve(other), threshold, ratio))
            verdict = "PASS" if ratio >= threshold else "FAIL"
            if verdict == "FAIL":
                violated.add(target)
            report.append(f"  {verdict}  {ratio:5.2f}:1  (needs {threshold})  "
                          f"{appearance:<5} {fg_path} on {bg_path}")

        for target in sorted(violated):
            reqs = constraints[target]
            family, step = ramp_of(target)
            worst = min(reqs, key=lambda r: r[3])

            if (appearance, target) in ACCEPTED:
                report.append(f"  KEEP  {target} ({appearance}) — accepted at "
                              f"{worst[3]:.2f}:1 vs {worst[0]}, not re-pointed")
                notes.append(f"/* ACCEPTED FAILURE — {target} keeps its source value in "
                             f"{appearance}: {worst[3]:.2f}:1 vs {worst[0]}, needs "
                             f"{worst[2]}:1. {ACCEPTED[(appearance, target)]} */")
                continue

            solution = next(((key, hex_) for key, hex_ in (ramp(family, step) if family else [])
                             if all(contrast(hex_, other) >= threshold
                                    for _, other, threshold, _ in reqs)), None)

            if not solution:
                report.append(f"  GAP   {target} ({appearance}) — no step of `{family}` "
                              f"satisfies all {len(reqs)} constraint(s), NOT FIXED")
                notes.append(f"/* PALETTE GAP — {target} needs "
                             + ", ".join(f"{t}:1 vs {p}" for p, _, t, _ in reqs)
                             + f"; best today is {worst[3]:.2f}:1 vs {worst[0]}. No step of "
                             f"the `{family}` ramp satisfies it — needs a new primitive. */")
                continue

            key, hex_ = solution
            achieved = ", ".join(f"{contrast(hex_, other):.2f}:1 vs {p}"
                                 for p, other, _, _ in reqs)
            overrides.append((PUBLIC + slug(target), f"var({PRIVATE}{slug(f'{family}.{key}')})",
                              achieved))
            report.append(f"  FIX   {target} ({appearance}) -> {family}.{key}  [{achieved}]")

        if overrides:
            selector = ':root, :root[data-appearance="grey"]' if appearance == "light" \
                else ':root[data-appearance="dark"]'
            body = "".join(f"  {name}: {value};  /* {why} */\n"
                           for name, value, why in sorted(set(overrides)))
            sections.append(f"/* {appearance} */\n{selector} {{\n{body}}}\n")
        if notes:
            sections.append("\n".join(notes) + "\n")

    out = BANNER.format(src=f"{CORE} + {EXT} (contrast pass)")
    out += ("/* Every declaration below is a measured WCAG failure in the sources as\n"
            "   they stand, re-pointed to the nearest step of its OWN ramp that clears\n"
            "   the threshold. Nothing is invented — each line is a one-line change to\n"
            "   make in Figma, after which this file shrinks.\n"
            "   4.5:1 = WCAG 1.4.3 (text) · 3:1 = WCAG 1.4.11 (UI component boundary).\n"
            "   Load AFTER tokens.ext.css. Remove the <link> to see the sources' own\n"
            "   values. Each fix here is an instance of gap G-01. */\n\n")
    out += "\n".join(sections) if sections else "/* No failures — nothing to override. */\n"
    return out, report


# ------------------------------------------------------------- dangling-var check

CONSUMERS = ["css/components.css", "index.html", "app.js"]

DEFINED_RE = re.compile(r"^\s*(--[\w-]+)\s*:", re.M)
USED_RE = re.compile(r"var\(\s*(--[\w-]+)")


def dangling_vars(outputs):
    """Names referenced with var() but declared nowhere.

    A token that lives only in the generated CSS and not in a source JSON
    disappears silently on the next build — the CSS still parses, the property
    just resolves to nothing and the component collapses. Catch it here."""
    text = "\n".join(outputs.values())
    for rel in CONSUMERS:
        path = ROOT / rel
        if path.exists():
            text += "\n" + path.read_text()

    defined = set(DEFINED_RE.findall(text))
    return sorted(set(USED_RE.findall(text)) - defined)


def private_leaks():
    """--_ds-* named outside the generated token layer. The one-way rule, enforced."""
    leaks = []
    for rel in CONSUMERS:
        path = ROOT / rel
        if not path.exists():
            continue
        # blank out comments first, keeping line numbers, so the house rule can
        # be written down in a header without the check tripping over it
        text = re.sub(r"/\*.*?\*/", lambda m: "\n" * m.group(0).count("\n"),
                      path.read_text(), flags=re.S)
        text = re.sub(r"<!--.*?-->", lambda m: "\n" * m.group(0).count("\n"),
                      text, flags=re.S)
        for number, line in enumerate(text.splitlines(), 1):
            if "--_ds-" in line:
                leaks.append(f"{rel}:{number}")
    return leaks


# ----------------------------------------------------------------------------- main

def main():
    check_only = "--check" in sys.argv

    collections = load_core()
    ext = json.loads((TOKENS / EXT).read_text())

    tokens_css, raw = build_tokens_css(collections)
    semantic_paths = {path for path, _ in
                      flatten(collections["Finlink Core Semantics"]["Light"])}
    a11y, report = build_a11y(collections, ext)

    outputs = {
        "tokens.css": tokens_css,
        "tokens.ext.css": build_ext(ext, set(raw), semantic_paths),
        "tokens.a11y.css": a11y,
    }

    dangling = dangling_vars(outputs)
    leaks = private_leaks()

    stale = []
    for filename, content in outputs.items():
        path = CSS / filename
        if check_only:
            if not path.exists() or path.read_text() != content:
                stale.append(filename)
        else:
            path.write_text(content)
            print(f"wrote css/{filename}  ({len(content.splitlines())} lines)")

    print("\ncontrast pass (WCAG 1.4.3 / 1.4.11):")
    print("\n".join(report))
    failures = sum(1 for line in report if line.strip().startswith(("FIX", "GAP")))
    accepted = sum(1 for line in report if line.strip().startswith("KEEP"))
    print(f"\n{failures} of {len(report)} measured pairs needed an override"
          + (f", {accepted} accepted as-is." if accepted else "."))

    if dangling:
        print("\nDANGLING var() references — used but declared nowhere:")
        print("\n".join(f"  {name}" for name in dangling))
        print("Add them to tokens/finlink-core-ext.json, or stop referencing them.")

    if leaks:
        print("\nPRIVATE TOKEN LEAK — --_ds-* named outside the token layer:")
        print("\n".join(f"  {where}" for where in leaks))
        print("Components consume semantic tokens only (contract law #2).")

    if check_only and stale:
        print("\nSTALE: " + ", ".join(stale))
        return 1
    if dangling or leaks:
        return 1
    if check_only:
        print("\nGenerated CSS is up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
